theme = "monokai"


[editor]
line-number = "relative"
mouse = false
cursorline = true
true-color = true
text-width = 220

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
[editor.lsp]
enable=true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
goto-reference-include-declaration = true

[keys.insert]
"A-d" = ["extend_to_line_bounds","yank","paste_after"]
"C-d" = ["extend_line_below","delete_selection"]
"A-down" = ["extend_to_line_bounds","delete_selection","paste_after"]
"A-up" =["extend_to_line_bounds","delete_selection","move_line_up","paste_before"]
S-A-down = ["extend_to_line_bounds", "yank", "open_below", "normal_mode", "replace_with_yanked", "collapse_selection"]
S-A-up = ["extend_to_line_bounds", "yank", "open_above", "normal_mode", "replace_with_yanked", "collapse_selection"]
[keys.normal]
"*" =["move_prev_word_start","move_next_word_end","search_selection","search_next"]
"@" = ["move_prev_word_start","move_next_word_end","search_selection","global_search"]
"s" = ["goto_word","move_prev_word_start"]
"C-s" = ":w"
"A-up" = ["extend_to_line_bounds","delete_selection","move_line_up","paste_before"]
"A-down" = ["extend_to_line_bounds","delete_selection","paste_after"]
"A-d" = ["extend_to_line_bounds","yank","paste_after"]
"C-d" = ["extend_line_below","delete_selection"]
S-A-down = ["extend_to_line_bounds", "yank", "open_below", "normal_mode", "replace_with_yanked", "collapse_selection"]
S-A-up = ["extend_to_line_bounds", "yank", "open_above", "normal_mode", "replace_with_yanked", "collapse_selection"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

